class Constants:
	DISTRIBUTION = "distribution"
	INDICES = "indices"
	LABELS = "labels"
	FRAME = "frame"
	FRAMES = "frames"
	CLASS = "class"
	BACKGROUND = "__background__"
	ANNOTATIONS = "annotations"
	MINI = "mini"
	METADATA = "metadata"
	SET = "set"
	VISIBLE = "visible"
	BOUNDING_BOX = "bbox"
	UNION_BOX = "union_box"
	PERSON_BOUNDING_BOX = "person_bbox"
	BOUNDING_BOX_SIZE = "bbox_size"
	STATE_DICT = "state_dict"
	FEATURES = "features"
	PAIR_IDX = "pair_idx"
	IM_IDX = "im_idx"
	HUMAN_IDX = "human_idx"
	IM_INFO = "im_info"
	UNION_FEAT = "union_feat"
	SPATIAL_MASKS = "spatial_masks"
	PRED_LABELS = "pred_labels"
	BOXES = "boxes"
	FMAPS = "fmaps"
	PRED_SCORES = "pred_scores"
	ATTENTION_DISTRIBUTION = "attention_distribution"
	SPATIAL_DISTRIBUTION = "spatial_distribution"
	CONTACTING_DISTRIBUTION = "contacting_distribution"
	ADAM = "adam"
	ADAMW = "adamw"
	SGD = "sgd"
	OBJECT_LOSS = "object_loss"
	FRAMES_PREDCLS = "frames_predcls"
	FRAMES_SGCLS = "frames_sgcls"
	FRAMES_SGDET = "frames_sgdet"
	
	GLOVE_6B = "glove.6B"
	
	SGDET = "sgdet"
	SGCLS = "sgcls"
	PREDCLS = "predcls"
	
	TRAIN = "train"
	TEST = "test"
	
	PREDCLS = "predcls"
	
	OBJECT_CLASSES_FILE = "object_classes.txt"
	RELATIONSHIP_CLASSES_FILE = "relationship_classes.txt"
	PERSON_BOUNDING_BOX_PKL = "person_bbox.pkl"
	OBJECT_BOUNDING_BOX_RELATIONSHIP_PKL = "object_bbox_and_relationship.pkl"
	PROGRESS_TEXT_FILE = "progress.txt"
	
	ATTENTION_RELATIONSHIP = "attention_relationship"
	SPATIAL_RELATIONSHIP = "spatial_relationship"
	CONTACTING_RELATIONSHIP = "contacting_relationship"
	
	ATTENTION_GT = "attention_gt"
	SPATIAL_GT = "spatial_gt"
	CONTACTING_GT = "contacting_gt"
	GLOBAL_OUTPUT = "global_output"
	
	ATTENTION_RELATION_LOSS = "attention_relation_loss"
	SPATIAL_RELATION_LOSS = "spatial_relation_loss"
	CONTACTING_RELATION_LOSS = "contacting_relation_loss"
	
	
